name = "tactics-eval"
defaultTargets = ["auto", "duper", "smt"]

[[lean_exe]]
name = "auto"
root = "Auto"
supportInterpreter = true

[[lean_exe]]
name = "duper"
root = "Duper"
supportInterpreter = true

[[lean_exe]]
name = "smt"
root = "Smt"
supportInterpreter = true

[[require]]
name = "smt"
scope = "ufmg-smite"
rev = "main"

[[require]]
name = "Duper"
scope = "leanprover-community"
rev = "main"
